/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include "main_window.h"
#include "data.h"

int main (int argc, char *argv[])
{
  gtk_init (&argc, &argv);
  cdata_init();
  main_window_init();
  cdata_get()->main_window_ui = main_window_run(cdata_get());
  gtk_main ();
  main_window_delete(cdata_get());
  cdata_delete();
  return 0;
}
