/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */
#include <gtk/gtk.h>
#include "main_window.h"
#include "data.h"

int main (int argc, char *argv[])
{
  cDATA *data;
  gtk_init (&argc, &argv);
  data = cdata_init();
  main_window_init();
  main_window_run(data);
  gtk_main ();
  main_window_delete(data);
  cdata_delete(data);
  return 0;
}
